apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: dryclean
    secureJsonData:
      password: dryclean_dev
    jsonData:
      database: dryclean_content
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: false

  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
